### PR TITLE
Remove `GitHub` prefix on ERB lint rules

### PR DESCRIPTION
**Pull request by khiga8**
This PR removes the `GitHub` prefix on rules because it is unnecessary/overly verbose.

### Discussion

I was discussing this idea with @manuelpuyol, and we think it might make sense to rename this gem and repo to `erblint-a11y`. The reason is because it may be much easier to gain attention/contributions from other folks interested in Rails/ERB accessibility tools. It may also be easier to collab on this with other Rails teams (like Shopify who open sourced erb-lint). 

Most of our ERB lint rules are a11y focused anyways so I am not sure how likely it is we'll open source other rules.
If we do rename this gem/repo, I think we'll want to it in the next-next release after adding a deprecation warning. Not totally sure what the best way to go about it would be.

Thoughts on this idea? cc: @joelhawksley ,  @github/accessibility-reviewers

### CODE REVIEW

**Review by inkblotty — APPROVED** [review]
IMO, I agree the rename could attract more contributors outside of GitHub and be an accelerator for this set of linting rules to grow and become more robust. 👍

**Review by bolonio — APPROVED** [review]

**Comment by bolonio** [comment]
> IMO, I agree the rename could attract more contributors outside of GitHub and be an accelerator for this set of linting rules to grow and become more robust. 👍

Definitely agree with @inkblotty, I like the idea of more open-source style without the GitHub prefix.

**Comment by joelhawksley** [comment]
👋🏻 thanks for the ping @khiga8!

I'm torn on this idea. On one hand, it does make sense to me given the current linters we've shipped. 

However, we do have several non-a11y linters we could open-source into this library and I worry that we'd be less likely to do so if we renamed it.

What if we moved towards contributing to `erblint` directly instead?

**Comment by manuelpuyol** [comment]
I think that this library can be a11y only. It would bring a lot of value to the community and reach a broader user base
we could still ship a github flavored ERB, similar to what we do with ESLint https://www.npmjs.com/package/eslint-plugin-github, which would use this gem (and probably some others)

**Comment by khiga8** [comment]
Thank you all for the input! I really appreciate it :)

> What if we moved towards contributing to erblint directly instead?

That is a good point. I think that would be a good eventual end-goal, but I might prefer us taking more ownership of these rules to start with. This would allow us to work more quickly and give greater input into the rulesets that are being introduced. Given our team's AOR, I feel that our team might be well-equipped to give input on the rulesets being introduced.

What do you think? @joelhawksley
I also don't think we need to make a decision immediately as we still need to build out this gem a bit more so happy to open an issue as we punt on it.

**Comment by joelhawksley** [comment]
> I think that would be a good eventual end-goal 

If we're confident enough to open-source these rules as we have already, I think it's a good enough sign that they could be proposed upstream for `erblint`. Maybe we try that and see how it goes? We can continue to explore new linters inside of GitHub.com either way.

**Comment by manuelpuyol** [comment]
>  think it's a good enough sign that they could be proposed upstream for `erblint`

I don't think we want to depend on them to release new linters. From my last conversation with them, it looks like the projects is maintained by a single person and from my experience it takes some time for the PRs to be reviewed/merged.

I think that having an a11y gem is a good idea so we can ship fast and also bring value to the community.

At some point, I do think it's worth exploring some kind of partnership with Shopify so we can help maintain erblint

**Comment by joelhawksley** [comment]
@manuelpuyol that's a good point. It would be good to be able to control releases. Have you asked about gaining publish rights on `erb-lint`?

Regardless, I think I see the point now. I'm 👍🏻 to rename.

**Comment by khiga8** [comment]
Thanks again everyone! 

There are some convos taking place next week that could affect trajectory of this convo so I'll hold off on naming until after the convos take place. 

I'll close this PR for now. I'll open a separate issue to follow up on the renaming.
🙇‍♀️

**Review by Saeed-ac — APPROVED** [review]

**Pull request closed without merging**
