### PR TITLE
Add new linter for inline CSS

### PR DESCRIPTION
**Pull request by langermank**
Copied from @jonrohan in https://github.com/primer/erblint-stylelint 

Adds a new linter for inline CSS

- Find inline `style` tags
- Run contents through Stylelint using Primer's config
- Warn about Primer CSS standards

Closes https://github.com/github/primer/issues/2348

### CODE REVIEW

**Comment by primer-css** [comment]
:wave: Hello and thanks for pinging us! This issue or PR has been added to our inbox and a Primer first responder will review it soon.
- :art: **If this is a PR that includes a visual change**, please make sure to add screenshots in the description or deploy this code to a lab machine with instructions for how to test.
- :fast_forward: **If this is a PR that includes changes to an interaction**, please include a [video recording](https://support.apple.com/en-us/HT208721) in the description.
- :warning: **If this is urgent**, please visit us in [#primer](https://github.slack.com/archives/CSGAVNZ19) on Slack and tag the first responders listed in the channel topic.

**Review by khiga8 — COMMENTED** [review]
One thought to start with - since this lint rule is Primer-specific, could it make sense for this rule to be part of existing [ERB linters exported by PVC](https://github.com/primer/view_components/tree/main/lib/primer/view_components/linters)?

**Comment by jonrohan** [comment]
> since this lint rule is Primer-specific,

It's not exactly primer specific, we were trying to come up with a way to run stylelint more broadly on `style=""` attributes which doesn't currently exist. It would be similar to writing a rule to run rubocop rules on ruby found it `<% ruby %>` erb files, does currently exist. 

That's why our first inclination was to put it as a separate repo https://github.com/primer/erblint-stylelint maybe would be useful for the community? 🤷🏻

**Review by khiga8 — COMMENTED** [review]
@jonrohan I see!

I notice there's a stylelint config added to this repo, along with a `npm install` call in the CI step. 

If I'm understanding correctly, the consuming application of this rule would have to make sure to install stylelint npm dependencies as a step in their lint workflow, and would also have to provide their own stylelint config in order to run this rule, right? It looks like the setup here doesn't carry over when this rule is called by a consumer, but would appreciate confirmation! This rule is nested under `Primer` but it seems like it would just use whatever stylelint config is configured by the consuming application?

**Comment by langermank** [comment]
Closing as we moved this to dotcom 😄

**Pull request closed without merging**
